### ISSUE TITLE
Which license?

### ISSUE THREAD

**Issue by fra87** [Dilbert66/esphome-components#1]
Hello

Thank you for your component. Definitely going to try and include it in a personal project.

What is missing, however, is a proper licensing for this collection of items.

Personally I hope you are going to release it with an open license (MIT for instance), but of course being the author this is totally up to you :)

**Comment by Dilbert66** [comment]
I added the LGPL licensing since a lot of the code I used is licensed by the same terms.

**Comment by fra87** [comment]
Ok thank you :)
